# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_goodslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=20)),
                ('src1', models.CharField(max_length=100)),
                ('src2', models.CharField(max_length=100)),
                ('src3', models.CharField(max_length=100)),
                ('src4', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=40)),
                ('original_price', models.CharField(max_length=40)),
                ('index1', models.CharField(max_length=100)),
                ('index2', models.CharField(max_length=100)),
                ('index3', models.CharField(max_length=100)),
                ('index4', models.CharField(max_length=100)),
            ],
        ),
    ]
