# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20181109_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodslist',
            name='price',
            field=models.IntegerField(max_length=40),
        ),
    ]
