# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20181109_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodslist',
            name='price',
            field=models.CharField(max_length=40),
        ),
    ]
