# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20181110_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
